# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUN3wWCwt-YlyWDPBIgnmvYLDXE40Fti
"""

a=int(input("enter the value of a:"))
b=int(input("enter the value of b:"))
c=int(input("enter the value of c:"))
x=int(input("enter the value of x:"))
y=0
y = a*(x*x)+b*x+c;
print("for the values:a",a,"b",b,"c",c,"y is:",y)