# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUN3wWCwt-YlyWDPBIgnmvYLDXE40Fti
"""

#whether modelling using the Quadratic Equation
a = 5
b = 4
c = 6
x = 4.5
y = a * x ** 2 + b * x + c
print("for the values of ",a, " " ,b, " " , " " ,c)